# !! File must end with empty line !!
dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.92
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.92
- alias: mysql
  name: mysql
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.6.4
  # !! "alias: preview" must be last entry in dependencies array !!
  # !! Place custom dependencies above !!
- alias: preview
  name: ps-jx-preview-env
  repository: file://../ps-jx-preview-env
